# ── General Options ───────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────

# Set statusbar to the top
set-option -g status-position top

# Colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Give mouse control to resize panes
set -g mouse on

# Start window number on 1 instead of 0
set -g base-index 1

# Fix shift + enter in some scenarios
set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Allow focus events to trigger re-read buffers in nvim
set -g focus-events on


# ── Key Bindings ──────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────

# Change leader key
unbind C-b
set -g prefix C-a

# Reload this config
unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Split windows
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Pane selection
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Pane resizing
bind -n M-H resize-pane -L 2
bind -n M-L resize-pane -R 2
bind -n M-K resize-pane -U 2
bind -n M-J resize-pane -D 2


# ── Copy Mode ─────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after mouse drag


# ── Plugins ───────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum config
set -g @continuum-restore 'on'        # ← auto-restore on tmux start
set -g @continuum-save-interval '15'  # optional: auto-save every 15 min


# ── Theme (Catppuccin) ────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"


# ── TPM Init ──────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────────
run '~/.tmux/plugins/tpm/tpm'
